### ISSUE TITLE
WinDLL issue

### ISSUE THREAD

**Issue by AndrewDavis** [boppreh/mouse#1]
Change _winmouse.py line 12 to:

```
#user32 = ctypes.windll.user32
user32 = ctypes.WinDLL('user32', use_last_error = True)
```

Otherwise, I get:

>   File "mouse\_winmouse.py", line 152, in listen
>     mouse_hook = SetWindowsHookEx(WH_MOUSE_LL, mouse_callback, NULL, NULL)
> ArgumentError: argument 2: <type 'exceptions.TypeError'>: expected CFunctionType instance instead of CFunctionType

when calling mouse.hook().

https://stackoverflow.com/questions/38557655/python-windows-mouse-hook-crash#comment64524554_38557655

**Comment by boppreh** [comment]
Aha, that solves the mystery of another issue that was reported: https://github.com/boppreh/keyboard/issues/80

A fix is in the release v0.7.0.

Thank you!
