### ISSUE TITLE
[help with code] high cpu usage

### ISSUE THREAD

**Issue by skhrlx** [boppreh/mouse#109]
So, currently this is my code, i need to constantly check if the left mouse button is pressed, but, this code is taking about 25% of my CPU. How i can solve this problem?
-----------
import mouse

def main():

    while True:
        if mouse.is_pressed(button='left'):
            print('Left mouse is down!')
if __name__ == '__main__':
    main()

**Comment by re1von** [comment]
You can use callback:
```python
import mouse

if __name__ == '__main__':
    mouse.on_button(lambda: print('Left mouse is down!'), buttons=mouse.LEFT, types=mouse.DOWN)
    input('Press <Enter> to exit.\n')
```

**Comment by skhrlx** [comment]
Thanks bro! It solved my problem.
