### ISSUE TITLE
mouse.move doesnt accept a list 

### ISSUE THREAD

**Issue by Motzumoto** [boppreh/mouse#117]
Doing this:
```py
button_left = [400, 960]
button_middle = [480, 960]
button_right = [580, 960]
button_choices = [button_left, button_middle, button_right]
mouse.move(random.choice(button_choices))

TypeError: move() missing 1 required positional argument: 'y'
```

Is there some other way i can do this?

**Comment by mudkipdev** [comment]
`mouse.move` accepts `x` and `y` arguments. Have you considered doing the following?
```py
choice = random.choice(button_choices)
mouse.move(choice[0], choice[1])
```

**Comment by Motzumoto** [comment]
> `mouse.move` accepts `x` and `y` arguments. Have you considered doing the following?
> 
> ```python
> choice = random.choice(button_choices)
> mouse.move(choice[0], choice[1])
> ```

I have not considered that, thanks!
