### ISSUE TITLE
OSError: Unsupported platform 'Darwin'

### ISSUE THREAD

**Issue by kylefoley76** [boppreh/mouse#29]
I'm getting the following error message:

`Traceback (most recent call last):
  File "count_keystrokes.py", line 1, in <module>
    import keyboard, mouse
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mouse/__init__.py", line 51, in <module>
    raise OSError("Unsupported platform '{}'".format(_platform.system()))
OSError: Unsupported platform 'Darwin'`

**Comment by kylefoley76** [comment]
Actually, it looks like this module is only written for windows or linux and I have a mac.  I really want to encourage you to become a mac person.  They are such better computers.  They are faster, more reliable and easier to use.  What more could a software writer want?

**Comment by jtara1** [comment]
leave this issue open

I'd like to see support for macOS too, but I'll keep dual-boot on my pcs so I can adapt.

I'd really like to see support for recording and playing back mouse movement and input, thanks.

**Comment by ah3243** [comment]
Also agree, I develop on a mac, so really unfortunate that such a clean library isn't compatible..
