### ISSUE TITLE
mouse.on_double_click not working

### ISSUE THREAD

**Issue by Doom8890** [boppreh/mouse#3]
Hi,

I have the issue where callback passed to `mouse.on_double_click` isn't invoked. 

I took a quick peek and it seems that `handler `method defined in `mouse.on_button ` gets called twice successively. Each `ButtonEvent` passed to the handler has `button = 'left'` and `event_type = 'down'` members, instead of `button = 'left'` and `event_type = 'double'` which the `handler` checks for.

This is the code I'm talking about.
```
def on_button(callback, args=(), buttons=(LEFT, MIDDLE, RIGHT, X, X2), types=(UP, DOWN, DOUBLE)):
    """ Invokes `callback` with `args` when the specified event happens. """
    if not isinstance(buttons, (tuple, list)):
        buttons = (buttons,)
    if not isinstance(types, (tuple, list)):
        types = (types,)

    def handler(event):
        if isinstance(event, ButtonEvent):
            if event.event_type in types and event.button in buttons:
                callback(*args)
    _listener.add_handler(handler)
    return handler
```
I'm a little busy at the moment, but if I find time I'll make an attempt at fixing this.

**Comment by boppreh** [comment]
It seems Windows is not reporting double click events when a global event hook is registered.

I couldn't find a way to get these events reported, so it probably needs processing the left clicks and checking for interval. Note to self: the maximum interval to be considered a double click is available via the [`GetDoubleClickTime()`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646258(v=vs.85).aspx) win32 function.

Thanks for the report. I'm extremely busy at the moment, but I'll take a look when I can. Feel free to work on it too.

**Comment by Doom8890** [comment]
I modified `low_level_mouse_handler` callback  in `_winmouse.py` to calculate time difference between previous and current event and create new `ButtonEvent` of type `DOUBLE` if the difference is less or equal to the value returned by `GetDoubleClickTime`.

```
    GetDoubleClickTime = user32.GetDoubleClickTime

    ...

    previous_button_event = None # defined in global scope

    ...

    def low_level_mouse_handler(nCode, wParam, lParam):
        global previous_button_event

        struct = lParam.contents
        # Can't use struct.time because it's usually zero.
        t = time.time()

        if wParam == WM_MOUSEMOVE:
            event = MoveEvent(struct.x, struct.y, t)
        elif wParam == WM_MOUSEWHEEL:
            event = WheelEvent(struct.data / (WHEEL_DELTA * (2<<15)), t)
        elif wParam in buttons_by_wm_code:
            type, button = buttons_by_wm_code.get(wParam, ('?', '?'))
            if wParam >= WM_XBUTTONDOWN:
                button = {0x10000: X, 0x20000: X2}[struct.data]
            event = ButtonEvent(type, button, t)

            if (event.event_type == DOWN) and previous_button_event is not None:
                diff = int(round(event.time * 1000.0)) - int(round(previous_button_event.time * 1000.0))
                if diff <= GetDoubleClickTime():
                    event = ButtonEvent(DOUBLE, event.button, event.time)

            previous_button_event = event

        queue.put(event)
        return CallNextHookEx(NULL, nCode, wParam, lParam)
```
So far this works as intented and generates `UP, DOWN, DOUBLE, UP` event sequence which is a valid double click event sequence according to this [MSDN article](https://msdn.microsoft.com/en-us/library/windows/desktop/gg153548(v=vs.85).aspx).

What do you think of this solution?

**Comment by boppreh** [comment]
Thank you, that works great. It's added by commit bc8d989 .
