### ISSUE TITLE
Please push new PyPI release

### ISSUE THREAD

**Issue by heeplr** [boppreh/mouse#43]
The current stable version still suffers the segfault problem. The current master is more stable (for me) than current stable.
It would be awesome if there would be an update. If there are any concerns, maybe consider publishing a [pre release version](https://packaging.python.org/guides/distributing-packages-using-setuptools/#pre-release-versioning).

**Comment by boppreh** [comment]
Version 0.7.1 published. Thank you for your input, sorry it took so long.
