### ISSUE TITLE
Sending mouse events doesn't work.

### ISSUE THREAD

**Issue by angeloped** [boppreh/mouse#52]
Everything that simulate mouse event doesn't work, except on positioning/moving the cursor.
Listening to mouse event works fine.
My machine running on Debian 4.19.28-2 (2019-03-18) i686 GNU/Linux.

**Comment by davyvandervekens** [comment]
Sending mouse events also doesn 't work on my Ubuntu 18.04.4 LTS machine.

**Not working**

- mouse.click(button='left')
- mouse.right_click()
- mouse.double_click(button='left')
- mouse.press(button='left')
- mouse.release(button='left')


**Working fine**

mouse.move(0, 50, absolute=False, duration=1)

**Comment by EmetMet** [comment]
Same here!
Use Lackey that simulates mouse events with mouse.click(button='left')
Click doesn't work in Ubuntu LTS 18.04

**Comment by TyrelCB** [comment]
Same, using Ubuntu LTS 18.04

**Comment by MrQubo** [comment]
Same, Arch Linux with 5.6.15-zen2-1-zen kernel.

**Comment by MrQubo** [comment]
#58 fixes this issue for me. Could other commenters check if this issue is resolved by #58?

**Comment by linus-jansson** [comment]
This still seems to be a problem on Arch Linux x86_64  5.15.34-1-lts on mouse==0.7.1

`mouse.click(button="left") `
does not react
