### ISSUE TITLE
mouse.move not moving to correct coordinates

### ISSUE THREAD

**Issue by Underslash12** [boppreh/mouse#54]
When using mouse.move(), the coordinates are not correct, ie: if I have this:
```
mouse.move(0, 1080, absolute=True)
print(mouse.get_position())
```
it should go to the bottom left (which it does) yet getting the mouse position reveals its actually 863.
If I then do mouse.move(0, 863, absolute=True), it puts me at the bottom left again, further testing reveals it isn't going to the correct spot. This also happens on the x-axis, giving me a max of 1535.

**Comment by Underslash12** [comment]
I accidentally found the fix - make sure your program accounts for dpi scaling, you can fix this by using:
```
import ctypes
awareness = ctypes.c_int()
ctypes.windll.shcore.SetProcessDpiAwareness(2)
``` hopefully this saves someone a headache.

**Comment by danjcosg** [comment]
Thank you! I encountered this issue too, I would definitely consider including this solution in the Docs
