### ISSUE TITLE
Mouse no longer works after .play

### ISSUE THREAD

**Issue by na-stewart** [boppreh/mouse#55]
I noticed after using the play method, it completely breaks my mouse and I have to do a hard restart. Any remedy?

Windows 10

**Comment by danjcosg** [comment]
Have this issue to, although it goes away if I click on the start button a few times

**Comment by mari0sz** [comment]
last event is Button down right, but there is no "up" event (waiting for "up"?). Play events [:-1].

**Comment by totuni** [comment]
this works: 
events = list(mouse.record(button='right',target_types=('up',)))

 The examples have events = list(mouse.record(button='right',target_types=('down',)))   So I guess that buggers it up
